name: docs_helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
 
  dev_icons: ^1.0.0
  docx_template: ^0.4.0
  docx_viewer: ^0.2.1
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_highlight: ^0.7.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  lucide_icons: ^0.257.0
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  responsive_builder: ^0.7.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DejaVuSansMono.ttf
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
    
